language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

script:
    pyrus install pear/PHP_CodeSniffer
    phpenv rehash
    phpcs
    
notifications:
  email:
    recipients:
    - ricardol@microsoft.com
    on_success: never
    on_failure: always
